name: yolo_dummy_data
channels:
  - conda-forge
  - default
  - pytorch 
  - nvidia
dependencies:
  - python=3.10
  - pip
  - autopep8
  - flake8
  - ipykernel
  - ipywidgets
  - opencv
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - ultralytics
    - label-studio
